(use-modules (doclisp) (make))
(set-reader! doclisp-reader)
{{post {version #1}}
 {title In Response to Pie-onomics}
 {uuid f07daef3-6876-4287-8a08-3777a726e8e7}
 {published #"2026/07/06 05:04 +0100"}
 {description
  It is often said that the economy isn't a {q fixed pie}, but a growing pie or a machine for making pies or something like that.
  My general rule is that you should dismiss people who start talking about pies when trying to discuss the economy.
  They're probably just hungry.
  But the perspective they hold is perhaps as common as it is ill-defined and I think it merits some response.}
 {body
  {p
   First we should note that the economy is a fixed pie.
   You can think of a big pile of stuff.
   Everyone puts some stuff on the pile by working, everyone takes some stuff off by consuming.
   We might call this a zero sum game in that you can only get more out if someone else gets less out.}
  {p
   The question then arises, what about {q value creation} which is what these pieonomists are usually talking about.
   Well value is created in two ways generally.
   The first is by working to put stuff on the pile, and the second is by specialising trades.
   Specialising trades allows two people in specific jobs to produce more than each could alone then trade excess.
   For instance a farmer and a baker might produce more loaves of bread than two people who each try to both farm and bake.}
  {p
   If we consider how big the pile would be under the assumption a given person didn't exist, the idea the economy isn't a fixed pie boils down to the fact that not only would the pile not have what they put on, but others would not be able to put on as much as trades would be some amount less specialised.
   The result is that removing a person who takes off exactly as much as they put on could make everyone else poorer as the overall pile shrinks.
   In the form of an equation, the value in the pile goes from V to V + C + S, where C is the contribution through working, and S is the amount extra that everyone can produce thanks to specialisation.
   So a person could actually withdraw up to C + S from the pile before their participation in the economy is a net drain on everyone else.
   This would seem to validate the pieonomists' conclusion that some people should be paid more than they make to grow the economy.
   But of course, what they leave out is that S is generated by other people working.
   The only way a person can claim the full C + S is by depriving others of the products of their labour.
   Claiming C + 0.5S might seem a good deal, but attention aught to be paid on how this is achieved, specifically threatening to withdraw labour.
   The only reason you're able to demand more than you put on is by threatening to take no action and leave everyone else worse off due to the lack of S.
   If others were also free to withdraw labour, then this would be impossible.
   You would each have equal negotiating power and the logical conclusion would be each person taking only what they give.
   But in a system where the rich can withdraw labour while the poor cannot, the rich will claim as close as they can to the full bonus of specialisation and leave the poor with none of that generated wealth.
   It's no surprise that the people who defend the rich being paid as they are also attack tools such as unions and welfare that allow the poor to withdraw labour and might result in fairer pay.}}}
